/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package allinter;

import org.junit.Test;

import static org.hamcrest.Matchers.is;
import static org.junit.Assert.*;

public class AppTest {
    private static final String[] ARGS = new String[] { "--no-html-checker" };

    @Test public void testMain() throws Exception {
        assertThat(App.execute(ARGS), is(0));
    }
}
